### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by bpeck81** [rvkulikov/pg-deps-management#11]
What I run:
```
select public.deps_save_and_drop_dependencies(
  'public',
  'my_view',
  '{
    "dry_run": false,
    "verbose": true,
    "populate_materialized_view": false
  }'
);
```

I get this error outputted:
Failed to run sql query: cannot drop view my_view because other objects depend on it

**Comment by rvkulikov** [comment]
Probably related to #10 - I've just realized that functions are not supported by backup-restore system.
Can you describe which objects (function, procedures, triggers, rules) are depending on that view?

Currently working on #10 on support of functions, procedures, triggers and rules - release would be published in 3 days.
But maybe you have something else in your issue.

**Comment by bpeck81** [comment]
Didn't realize it doesn't work with functions, so it's probably because I have several functions dependent. If you could support that it would be immensely valuable. Idk how postgres isn't developed with this functionality in mind. 

Whatever you write to handle this issue should be incorporated into postgres's core. When I was a data and applied scientist at Microsoft we used something called kusto query language which automatically changed dependent schemas and abstracted developers from these issues. Postgres feels very rigid by comparison.

**Comment by rvkulikov** [comment]
Ok, so it is functions. Release would be published in 3 days.

**Comment by bpeck81** [comment]
Looking forward to it...

**Comment by rvkulikov** [comment]
Okay, so it is definitely will take *more* than 3 days to be done.
There is no information about which objects routine is depending on in pg_catalog.pg_depend table.
So there is only way to a) parse routine body to find related objects via regex b) use some kind of AST representation of routine body.

For now you should manually drop&restore your dependencies because I don't how much time it will take to solve routines.

Closing this issue in prior to #10 - progress (or lack of) will be tracked there.

Upd. there is no checks of references inside function body. The only pg_depend check was function's return type.
So it will be much easier to solve (no checks - no problems). 
Release would be published in 3 days (haha)
